travis:
  secure:
    BINSTAR_TOKEN: Z4qiHrVLcaIw/7Teln72KfRuLxYIMxgCQRXNanzB6ngyt1T9YUcLIqNgvzKZ9XnrLPBxqBPlrfJJ0Q+bQ64u4AKHUbi4PFlSkkXj+3StXfzDkwVamcYwvvXkMwos26cLhh0D4G9nCj/lmRy+tNoiE+9QUXSE0quENtvLaTORt6pjaaCT2WAwCFmDW1oRnPADOAj1SPcG5JL6rl+jEX/eEuuNFLnqmw555yXOCiS6AkRxLPQdbHtNmdHE+iAjVjx9ummLLW4MbulIF2GVzmCyKMZodxrEXu7K+c98onx17Eq+UqUQgGcpVgiwfMkmAkLEETCbZWNHfWrR4/dpkAcQkO7zlsprMJRIfp25dL5Ogbnly2b982B14SGDV2PN0ZbRMlRfztmJWZZrIhOZhihwXOp3ThtYukW7s6NFXyLbkdg8082QWEGCxcPr6xnNgxZysw1RsNg/e5i7W9Wm81GM5AJgceJZiBR7cTAHC0i+5Cz+5Bmu/gq6bwzKi/8M/larTz4CFWNUWtdiBdGIMCKG37oZSi3rXkwvIe9xdss9C29gLWm8XEbq/haZl+b7V8AUx8XIyLx9WRaXjDTviID2l/FzTNbV6NR6NLJlP1vxvw1ZWz3EqNSTw3xHeGJWgEkJpO5+WuC0oH9aceGt7DllP1UrKrl4iynFZIBGHslRNeI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
